name: ketter_app
description: "Ketter: A Personal Health Record app for oncology patients with Edge AI EWS."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fhir: ^0.12.0
  fl_chart: ^0.70.2
  flutter_local_notifications: ^17.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
